name: Docker Images Publish

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # 确保与 Secret 名称一致
        password: ${{ secrets.DOCKERHUB_TOKEN }}     # 确保与 Secret 名称一致

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Marker version and time
      id: getVersion
      run: |
        sed -i "s@COMMIT_HASH@$(git rev-parse --short HEAD)@" rootfs/Aria2-Pro
        sed -i "s@DATE_TIME@$(date +"%Y/%m/%d %H:%M")@" rootfs/Aria2-Pro
        cat rootfs/Aria2-Pro
        echo "time=$(date +"%Y%m%d%H%M")" >> $GITHUB_OUTPUT  # 注意：最新 GitHub Actions 推荐用这种输出方式

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
        file: Dockerfile
        context: .
        push: true
        tags: |
          p3terx/aria2-pro:latest
          ghcr.io/p3terx/aria2-pro:latest
          p3terx/aria2-pro:${{ steps.getVersion.outputs.time }}
          ghcr.io/p3terx/aria2-pro:${{ steps.getVersion.outputs.time }}
